name: liqui_walls
description: A wallpaper dashboard app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  supercharged: ^1.10.0
  auto_route: ^0.6.9
  animations: ^1.1.2
  sliding_up_panel: ^1.0.2
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  get: ^3.15.0
  cached_network_image: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Circular-Std
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Book.ttf
          weight: 300
