name: liqui_walls
description: A wallpaper dashboard app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  supercharged: ^1.10.0
  auto_route: ^0.6.9
  animations: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner:

flutter:
  uses-material-design: true
